version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/app_db

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: